# Generated by Django 5.2.3 on 2025-06-15 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarAdvertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('kilometer', models.IntegerField()),
                ('fuel_type', models.CharField(choices=[('Benzin', 'Benzin'), ('Dizel', 'Dizel'), ('LPG', 'LPG'), ('Elektrik', 'Elektrik'), ('Hibrit', 'Hibrit')], max_length=20)),
                ('transmission', models.CharField(choices=[('Manuel', 'Manuel'), ('Otomatik', 'Otomatik'), ('Yarı Otomatik', 'Yarı Otomatik')], max_length=20)),
                ('engine_power', models.IntegerField(help_text='HP')),
                ('engine_size', models.FloatField(help_text='cc')),
                ('color', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_images/')),
                ('is_primary', models.BooleanField(default=False)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='advertisements.caradvertisement')),
            ],
        ),
    ]
