# Generated by Django 4.2.23 on 2025-08-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caradvertisement',
            name='brand',
            field=models.CharField(choices=[('BMW', 'BMW'), ('AUDI', 'AUDI')], max_length=100),
        ),
    ]
